version: "3.8"
services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    env_file:
      - .env-dev
    ports:
      - 5432:5432
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: "true"
    command: "/app/start-dev.sh"
    volumes:
      - "./backend/app/:/app"
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env-dev
  object-storage:
    image: minio/minio:RELEASE.2020-12-12T08-39-07Z
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data
    command: server /data

volumes:
  minio-data:
