"""added new db table for documents

Revision ID: edc3dc2fa9e2
Revises: f42bc8b30dbe
Create Date: 2020-12-15 12:14:47.371604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edc3dc2fa9e2'
down_revision = 'f42bc8b30dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('md5_sum', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dataroom_fk', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dataroom_fk'], ['dataroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_created_at'), 'document', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_file_name'), 'document', ['file_name'], unique=False)
    op.create_index(op.f('ix_document_id'), 'document', ['id'], unique=False)
    op.create_index(op.f('ix_document_md5_sum'), 'document', ['md5_sum'], unique=False)
    op.create_index(op.f('ix_document_name'), 'document', ['name'], unique=True)
    op.create_index(op.f('ix_document_updated_at'), 'document', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_updated_at'), table_name='document')
    op.drop_index(op.f('ix_document_name'), table_name='document')
    op.drop_index(op.f('ix_document_md5_sum'), table_name='document')
    op.drop_index(op.f('ix_document_id'), table_name='document')
    op.drop_index(op.f('ix_document_file_name'), table_name='document')
    op.drop_index(op.f('ix_document_created_at'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
